package com.cooksys.models;
// Generated Feb 15, 2016 3:01:24 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "friend", catalog = "jitter")
public class Friend implements java.io.Serializable {

	private Integer id;
	private Jitterer jittererByFriend;
	private Jitterer jittererByJitterer;
	private short follow;

	public Friend(){
	}

	public Friend(Jitterer jittererByFriend, Jitterer jittererByJitterer, short follow) {
		this.jittererByFriend = jittererByFriend;
		this.jittererByJitterer = jittererByJitterer;
		this.follow = follow;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "friend", nullable = false)
	public Jitterer getJittererByFriend() {
		return this.jittererByFriend;
	}

	public void setJittererByFriend(Jitterer jittererByFriend) {
		this.jittererByFriend = jittererByFriend;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jitterer", nullable = false)
	public Jitterer getJittererByJitterer() {
		return this.jittererByJitterer;
	}

	public void setJittererByJitterer(Jitterer jittererByJitterer) {
		this.jittererByJitterer = jittererByJitterer;
	}

	@Column(name = "follow", nullable = false)
	public short getFollow() {
		return this.follow;
	}

	public void setFollow(short follow) {
		this.follow = follow;
	}

}
