package com.cooksys.models;
// Generated Feb 15, 2016 3:01:24 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jitter generated by hbm2java
 */
@Entity
@Table(name = "jitter", catalog = "jitter")
public class Jitter implements java.io.Serializable {

	private Integer id;
	private Jitterer jitterer;
	private String jitter;

	public Jitter() {
	}

	public Jitter(Jitterer jitterer, String jitter, Date ts) {
		this.jitterer = jitterer;
		this.jitter = jitter;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jitterer_id", nullable = false)
	public Jitterer getJitterer() {
		return this.jitterer;
	}

	public void setJitterer(Jitterer jitterer) {
		this.jitterer = jitterer;
	}

	@Column(name = "jitter", nullable = false, length = 65535)
	public String getJitter() {
		return this.jitter;
	}

	public void setJitter(String jitter) {
		this.jitter = jitter;
	}

}
